/*
 *  Copyright Jóannes í Sandagerði 2014
 */
package com.sandagerdi.translationprojectmanager.Models;

import com.sandagerdi.translationprojectmanager.Repository.DatabaseConnection;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;

class exitHandler {

    public static void exitApp(DatabaseConnection db){
        db.Disconnect();
        System.exit(0);
    }   
}


class MenuAction extends AbstractAction{
    DatabaseConnection db;
    public MenuAction(String text, ImageIcon icon,
                      String desc, Integer mnemonic, DatabaseConnection db) {
        super(text, icon);
        putValue(SHORT_DESCRIPTION, desc);
        putValue(MNEMONIC_KEY, mnemonic);
        this.db = db;
    }
//    §
    @Override
    public void actionPerformed(ActionEvent e) {
        exitHandler.exitApp(db);
    }

}

/**
 *
 * @author Jóannes
 */
public class UI extends javax.swing.JFrame {
    // Variables declaration               
    private com.sandagerdi.translationprojectmanager.Models.AddNewJobPanel addNewJobPanel1;
    private com.sandagerdi.translationprojectmanager.Models.ClientPanel clientPanel2;
    private javax.swing.JMenu mainMenuFile;
    private javax.swing.JMenu mainMenuEdit;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenuItem file;
    private javax.swing.JTabbedPane tabs;
    private com.sandagerdi.translationprojectmanager.Models.JobTypesPanel jobTypesPanel1;
    private com.sandagerdi.translationprojectmanager.Models.ViewClientsTable viewClientsTable1;
    private com.sandagerdi.translationprojectmanager.Models.ViewJobTypesTable viewJobTypesTable1;
    // End of variables declaration                   

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }


    DatabaseConnection db = new DatabaseConnection();
    // get a logger instance named "com.foo"
    Logger  logger = Logger.getLogger("translator");
    private ViewJobsTable viewJobsTable;
    /**
     * Creates new form FUCKYOU
     */
    public UI() {
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        db.setupDatabase();
        initComponents();
        //Initialize the database
        addWindowListener(new WindowListener() {

            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
                exitHandler.exitApp(db);
            }

            @Override
            public void windowClosed(WindowEvent e) {
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        viewClientsTable1 = new com.sandagerdi.translationprojectmanager.Models.ViewClientsTable();
        jobTypesPanel1 = new com.sandagerdi.translationprojectmanager.Models.JobTypesPanel();
        viewJobTypesTable1 = new com.sandagerdi.translationprojectmanager.Models.ViewJobTypesTable();
        clientPanel2 = new com.sandagerdi.translationprojectmanager.Models.ClientPanel();
        addNewJobPanel1 = new com.sandagerdi.translationprojectmanager.Models.AddNewJobPanel();
        viewJobsTable = new com.sandagerdi.translationprojectmanager.Models.ViewJobsTable();
        mainMenuBar = new javax.swing.JMenuBar();
        mainMenuFile = new javax.swing.JMenu();
        mainMenuEdit = new javax.swing.JMenu();
        file = new javax.swing.JMenuItem();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabs.addTab("See Jobs", viewJobsTable);
        tabs.addTab("Add Jobs", addNewJobPanel1);
        
        tabs.addTab("See Job Types", viewJobTypesTable1);
        tabs.addTab("Add Job Types", jobTypesPanel1);
        
        tabs.addTab("See Clients", viewClientsTable1);
        tabs.addTab("Add Clients", clientPanel2);
                
        mainMenuFile.setText("File");

        file.setAction(new MenuAction("Exit", new ImageIcon(), "", KeyEvent.VK_L, db));
        
        mainMenuFile.add(file);

        mainMenuBar.add(mainMenuFile);
        
        mainMenuEdit.setText("Edit");
        mainMenuBar.add(mainMenuEdit);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        );

        pack();
        
        
    }
    
    public void exitApplication(DatabaseConnection db){
        db.Disconnect();
        System.exit(0);
    }

    
}

